#!/bin/bash

# GoPay QRIS Payment Server - Auto Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/arivpnstores/PUBLIC-GOPAY-PAYMENT/main/install.sh | bash

set -e

REPO_URL="https://github.com/arivpnstores/PUBLIC-GOPAY-PAYMENT.git"  # Ganti dengan repo URL asli
PROJECT_DIR="PUBLIC-GOPAY-PAYMENT"
PM2_APP_NAME="gopay-qris-server"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check requirements
check_requirements() {
    log "Checking requirements..."
    
    for cmd in git node npm pm2; do
        if ! command -v $cmd &> /dev/null; then
            error "$cmd tidak ditemukan. Install dulu: "
            case $cmd in
                git) echo "  apt install git / brew install git" ;;
                node) echo "  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt install nodejs" ;;
                npm) echo "  (comes with node)" ;;
                pm2) echo "  npm install -g pm2" ;;
            esac
            exit 1
        fi
    done
    success "All requirements met"
}

# Clone or update repo
setup_repo() {
    if [ -d "$PROJECT_DIR" ]; then
        log "Directory $PROJECT_DIR sudah ada, pull latest..."
        cd "$PROJECT_DIR"
        git pull origin main
    else
        log "Cloning repository..."
        git clone "$REPO_URL" "$PROJECT_DIR"
        cd "$PROJECT_DIR"
    fi
    success "Repo ready"
}

# Install npm dependencies
install_deps() {
    log "Installing npm dependencies..."
    npm install
    success "Dependencies installed"
}

# Setup .env interactively
setup_env() {
    log "Setting up .env configuration..."
    
    if [ -f .env ]; then
        warn ".env sudah ada"
        read -p "Overwrite? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log "Melewati setup .env"
            return
        fi
    fi
    
    echo
    echo "=== Konfigurasi GoMerch ==="
    echo "Dapatkan nilai ini dari dashboard GoMerch"
    echo
    
    read -p "BASE_URL [https://qris.adijayavpnpedia.cloud]: " BASE_URL
    BASE_URL=${BASE_URL:-https://qris.adijayavpnpedia.cloud}
    
    read -p "MERCHANT_ID: " MERCHANT_ID
    while [ -z "$MERCHANT_ID" ]; do
        error "MERCHANT_ID wajib diisi!"
        read -p "MERCHANT_ID: " MERCHANT_ID
    done
    
    read -p "ACCESS_TOKEN (JWT): " ACCESS_TOKEN
    while [ -z "$ACCESS_TOKEN" ]; do
        error "ACCESS_TOKEN wajib diisi!"
        read -p "ACCESS_TOKEN (JWT): " ACCESS_TOKEN
    done
    
    read -p "REFRESH_TOKEN (JWT): " REFRESH_TOKEN
    while [ -z "$REFRESH_TOKEN" ]; do
        error "REFRESH_TOKEN wajib diisi!"
        read -p "REFRESH_TOKEN (JWT): " REFRESH_TOKEN
    done
    
    read -p "STATIC_QR (string QR dari GoMerch): " STATIC_QR
    while [ -z "$STATIC_QR" ]; do
        error "STATIC_QR wajib diisi!"
        read -p "STATIC_QR (string QR dari GoMerch): " STATIC_QR
    done
    
    read -p "PORT [2234]: " PORT
    PORT=${PORT:-2234}
    
    cat > .env <<EOF
# GoPay QRIS Payment Server Configuration
# Generated by install.sh on $(date -Iseconds)

BASE_URL=$BASE_URL
MERCHANT_ID=$MERCHANT_ID
ACCESS_TOKEN=$ACCESS_TOKEN
REFRESH_TOKEN=$REFRESH_TOKEN
STATIC_QR=$STATIC_QR
PORT=$PORT
EOF
    
    success ".env created"
}

# Start with PM2
start_pm2() {
    log "Starting server with PM2..."
    
    # Stop existing if any
    pm2 stop "$PM2_APP_NAME" 2>/dev/null || true
    pm2 delete "$PM2_APP_NAME" 2>/dev/null || true
    
    # Start new
    pm2 start server.js --name "$PM2_APP_NAME" --time
    pm2 save
    
    success "Server started with PM2"
    pm2 status "$PM2_APP_NAME"
}

# Show info
show_info() {
    PORT=$(grep ^PORT= .env | cut -d'=' -f2)
    PORT=${PORT:-2234}
    
    echo
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║     Installasi Selesai!                                      ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo
    echo "Server berjalan di PM2: $PM2_APP_NAME"
    echo
    echo "Endpoint:"
    echo "  Create QRIS:  http://localhost:$PORT/createqris/amount=1000"
    echo "  Cek Bayar:    http://localhost:$PORT/cekpembayaran/:checkId"
    echo
    echo "PM2 Commands:"
    echo "  pm2 status              - Cek status"
    echo "  pm2 logs $PM2_APP_NAME  - Lihat log"
    echo "  pm2 restart $PM2_APP_NAME - Restart"
    echo "  pm2 stop $PM2_APP_NAME    - Stop"
    echo "  pm2 monit               - Monitor real-time"
    echo
    echo "Dokumentasi: README.md"
}

# Main
main() {
    echo
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║     GoPay QRIS Payment Server - Auto Installer              ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo
    
    check_requirements
    setup_repo
    install_deps
    setup_env
    start_pm2
    show_info
}

main "$@"